[article]
Title = "Being Social Media Friendly"
Tags = ["go"]
Published = 2021-12-28T09:52:27Z

[meta]
Description = "The first out-of-the-roadmap update for my blogging (static site generator) system."
